<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\ErmayMuhasebe.Shared\ErmayMuhasebe.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="sqlite-net-pcl" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
