name: Connect to macOS Terminal and Desktop (Live)

on:
  workflow_dispatch:

jobs:
  macos-session:
    name: Live macOS Session
    runs-on: macos-14

    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v4

      - name: 🌐 Start Live Web Terminal (Tmate)
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
